---
- name: cups_pdf | Install cups-pdf package
  ansible.builtin.package:
    name: cups-pdf
    state: present
  become: true
- name: cups_pdf | Configure cups-pdf
  ansible.builtin.lineinfile:
    path: /etc/cups/cups-pdf.conf
    line: "{{ item }}"
    regexp: "^{{ item | regex_replace(' .*', ' ') }}.*"
    insertafter: "^#{{ item | regex_replace(' .*', ' ') }}.*"
  loop: "{{ system_print_cups_pdf_config }}"
  become: true
