---
# tasks file for system_print

- name: Make sure cupsd is installed
  ansible.builtin.package:
    name: cups
    state: present
  become: true

- name: Configure CUPS server(s)
  ansible.builtin.lineinfile:
    create: true
    dest: "/etc/cups/cups-browsed.conf"
    line: "BrowsePoll {{ item }}"
    mode: "0644"
  loop: "{{ system_print_cups_servers }}"
  become: true
  notify:
    - restart_cups_browsed

- name: Enable and start cups-browsed
  ansible.builtin.service:
    name: cups-browsed
    enabled: true
    state: started
  become: true

# TODO: enable ipp-client in firewall? (according to cups-browsed.conf)

- name: Import task file to install and configure cups-pdf
  ansible.builtin.include_tasks:
    file: cups_pdf.yml
    apply:
      become: true
  when: system_print_cups_pdf_config is defined
