---
# tasks file for system_print

- name: make sure cupsd is installed
  ansible.builtin.package:
    name: cups
    state: present

- name: configure CUPS server(s)
  ansible.builtin.lineinfile:
    create: true
    dest: "/etc/cups/cups-browsed.conf"
    line: "BrowsePoll {{ item }}"
    mode: "0644"
  with_items: "{{ cups_servers | default([]) }}"
  notify:
    - restart_cups_browsed

- name: enable and start cups-browsed
  ansible.builtin.service:
    name: cups-browsed
    enabled: true
    state: started

# TODO: enable ipp-client in firewall? (according to cups-browsed.conf)

- name: import task file to install and configure cups-pdf
  ansible.builtin.include_tasks:
    file: cups_pdf.yml
  when: cups_pdf_config is defined
