---
# tasks file for system_software
- name: install packages required by default tasks
  ansible.builtin.dnf:
    name: "{{ software_fedora_mandatory }}"
    state: present
- name: install additional Fedora packages
  ansible.builtin.dnf:
    name: "{{ software_fedora_additional }}"
    state: present
- name: import tasks to enable and install packages from RPM Fusion
  ansible.builtin.import_tasks:
    file: rpmfusion.yml
  when:
    - rpmfusion_licenses is defined
    - software_rpmfusion is defined
