---
# tasks file for system_software
- name: install packages required by default tasks
  ansible.builtin.dnf:
    name: "{{ system_software_mandatory }}"
    state: present
  become: true
- name: install additional Fedora packages
  ansible.builtin.dnf:
    name: "{{ system_software_additional }}"
    state: present
    allowerasing: "{{ system_software_erase }}"
  become: true
- name: import tasks to enable and install packages from RPM Fusion
  ansible.builtin.include_tasks:
    file: rpmfusion.yml
  when:
    - system_software_licenses is defined
    - system_software_rpmfusion is defined
