---
- name: "rpmfusion | setup repository/ies {{ rpmfusion_licenses | join(' and ') }}"
  ansible.builtin.dnf:
    disable_gpg_check: true
    name: "http://download1.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ fedora_release }}.noarch.rpm"
    state: present
  loop: "{{ rpmfusion_licenses }}"
  become: true
- name: rpmfusion | install packages from RPM Fusion
  ansible.builtin.dnf:
    name: "{{ software_rpmfusion }}"
    state: present
  become: true
