---
# tasks file for user_software_vscode
# https://computingforgeeks.com/install-visual-studio-code-on-fedora/

- name: include extension handling task file
  ansible.builtin.include_tasks:
    file: extension.yml
  loop: "{{ software_vscode_extensions }}"
