---
# tasks file for system_user
- name: create user {{ local_username }}
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.description | default(omit) }}"
    uid: "{{ item.id | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    password: "{{ item.password | default('!') }}"
    state: "{{ item.state | default(omit) }}"
    append: true
  loop: "{{ local_users }}"
- name: Add polkit rule to allow libvirt usage by group {{ local_admin_group }}
  ansible.builtin.template:
    src: templates/polkit-libvirt.rules.j2
    dest: /etc/polkit-1/rules.d/80-libvirt.rules
    owner: root
    group: root
    mode: u=rw,go=r
  when: local_admin_group is defined
