---
# tasks file for system_tuxedo
- name: present | Tuxedo repository is created
  ansible.builtin.copy:
    src: tuxedo.repo
    dest: /etc/yum.repos.d/tuxedo.repo
    mode: "0644"
  become: true
- name: present | Facts are gathered if not yet done
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - 'distribution_version'
  when:
    - ansible_distribution_version is not defined  # used in system_tuxedo_rpm_key
- name: present | Repository key is imported
  ansible.builtin.rpm_key:
    key: "{{ system_tuxedo_rpm_key }}"
    state: present
  become: true
- name: present | Necessary packages are installed
  ansible.builtin.dnf:
    name: "{{ system_tuxedo_packages }}"
    state: present
    update_cache: true
  become: true
