---
# tasks file for user_desktop

- name: desktop_gnome | Activate the Gnome Shell extensions
  ansible.builtin.command:
    cmd: gnome-shell-extension-tool -e "{{ item }}"
  loop: "{{ user_desktop_gnome_shell_extensions }}"
  register: __user_desktop_res
  changed_when: not "is already enabled" in __user_desktop_res.stderr
  failed_when:
    - not "is already enabled" in __user_desktop_res.stderr
    - __user_desktop_res.rc != 0
