---
- name: desktop_xfce | Include xfconf to query and set each configuration item
  ansible.builtin.include_tasks:
    file: desktop_xfce_xfconf.yml
  loop: "{{ user_desktop_xfce_configs }}"
  loop_control:
    loop_var: xfce_conf
