---
- name: desktop_xfce_xfconf | Create variable from channel and property
  ansible.builtin.set_fact:
    __user_desktop_xfce_conf: "{{ xfce_conf.chan }}/{{ xfce_conf.prop }}"
- name: desktop_xfce_xfconf | Check the current value of {{ __user_desktop_xfce_conf }}
  ansible.builtin.command:
    cmd: xfconf-query --channel {{ xfce_conf.chan }} --property {{ xfce_conf.prop }}
  register: xfconf_query
  changed_when: false
  check_mode: false
- name: desktop_xfce_xfconf | Set {{ __user_desktop_xfce_conf }}
  ansible.builtin.command:
    cmd: >
      xfconf-query --channel {{ xfce_conf.chan }}
      --property {{ xfce_conf.prop }} --set "{{ xfce_conf.value }}"
  when: xfconf_query.stdout != xfce_conf.value
  changed_when: true  # there is probably always a change
