---

- name: dictionaries | move away unnecessary dictionaries
  ansible.builtin.command:
    argv:
      - mv
      - "{{ item }}"
      - "{{ item }}~"
  args:
    removes: "{{ item }}"
    creates: "{{ item }}~"
  with_fileglob: "{{ system_locale_dictionaries_globs }}"
  when: not (item | regex_search(system_locale_keep_dicts_langs | join("|")))

- name: dictionaries | move back necessary dictionaries
  ansible.builtin.command:
    argv:
      - mv
      - "{{ item }}"
      - "{{ item | regex_replace('~$', '') }}"
  args:
    removes: "{{ item }}"
    creates: "{{ item | regex_replace('~$', '') }}"
  with_fileglob: "{{ system_locale_dictionaries_globs_tilde }}"
  when: item | regex_search(system_locale_keep_dicts_langs | join("|"))
