---
# tasks file for system_locale
- name: "gather current X11 Keymap"
  ansible.builtin.command: localectl status
  register: locale_before
  changed_when: false

- name: "setup X11 Keymap Locale"
  ansible.builtin.command: >
    localectl set-x11-keymap
    {{ locale_keymap.layout }} {{ locale_keymap.model }}
    {{ locale_keymap.variant }} {{ locale_keymap.options }}
  when: locale_keymap is defined
  changed_when: false

- name: "verify if new X11 Keymap changed"
  ansible.builtin.command: localectl status
  register: locale_after
  changed_when: locale_after.stdout != locale_before.stdout
  when: locale_keymap is defined

- name: import dictionaries tasks
  ansible.builtin.include_tasks:
    file: dictionaries.yml
  when: locale_keep_dicts_langs is defined
