---
# tasks file for system_wlan

- name: include correct WLAN method
  ansible.builtin.include_tasks:
    file: "{{ system_wlan_method }}.yml"
  vars:
    __system_wlan_config_dir: "{{ system_wlan_config_dir[system_wlan_method] }}"
