---
# defaults file for inventory_create

# base directory of the inventory of hosts and variables to create
# by default in the same directory as the 'playbooks' directory,
# with a name to be ignored by Git.
inventory_create_base_dir: "{{ playbook_dir | dirname }}/inventory.myown.d"

# name of the host to add to the inventory
inventory_create_hostname: "{{ fedora_desktop_hostname | default(inventory_hostname) }}"

# directory of the newly created host in the inventory
inventory_create_host_dir: "{{ inventory_create_base_dir }}/host_vars/{{ inventory_create_hostname }}"

# in which inventory group to put the new hosts
inventory_create_default_group: fedoras

# if an inventory already exists, overwrite existing files with defaults
inventory_create_force: false

# if an inventory already exists, create a backup of modified files
inventory_create_backup: true
