---
# vars file for system_vagrant
# list of vagrant plugins packaged in Fedora
system_vagrant_plugins:
  - vagrant-libvirt  # libvirt provider
  - vagrant-cachier  # plugin to cache packages
  - vagrant-hostmanager  # plugin to manage /etc/hosts
  - vagrant-openstack-provider  # plugin for OpenStack provider
  - vagrant-sshfs  # synced folder plugin that mounts folders via SSHFS
  - vagrant-digitalocean  # plugin for Digital Ocean as a provider
  - vagrant-registration  # plugin for automatic guest registration

# list of RPM packaged required to compile Vagrant plug-ins locally
system_vagrant_plugin_deps:
  - ruby-devel
  - rubygem-rexml
