---
# tasks file for system_power

- name: Install power management software
  ansible.builtin.package:
    name: "{{ system_power_packages }}"
    state: present
  become: true
- name: Power tune your system and optionally calibrate (screen might flicker)
  ansible.builtin.command:
    cmd: >-
      powertop {% if system_power_calibrate %}--calibrate{% endif %} --auto-tune
  when: system_power_autotune
  changed_when: true  # just keeping ansible-lint happy
  become: true
- name: Enable and start tlp service
  ansible.builtin.service:
    name: tlp
    state: started
    enabled: true
  become: true
