---
# tasks file for system_vagrant
- name: install | Block install of vagrant libvirt to avoid mix-up of plug-ins
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'excludepkgs={{ system_vagrant_plugins | join(",") }}'
    regexp: '^excludepkgs='
    insertafter: '\[main\]'
    state: present
  when: system_vagrant_block_plugins
  become: true
- name: install | Uninstall vagrant-libvirt RPM if plug-in mix-up to be avoided
  ansible.builtin.package:
    name: "{{ system_vagrant_plugins }}"
    state: absent
  when: system_vagrant_block_plugins
  become: true
- name: install | Install standard vagrant RPM
  ansible.builtin.package:
    name: vagrant
    state: present
  become: true
- name: install | Install dependencies for building native plug-ins
  ansible.builtin.package:
    name: >-
      {{ system_vagrant_plugin_deps
      | union(system_vagrant_plugin_own_deps) | unique }}
    state: present
  when: system_vagrant_block_plugins
  become: true
