---
# handlers file for system_wlan
- name: reload all connection files from disk
  ansible.builtin.command:
    cmd: nmcli connection reload
  listen: reload_connections
  changed_when: false  # doesn't really change anything
