---
- name: content | Create the user's config file
  ansible.builtin.copy:
    backup: false
    content: "{{ config_item.content }}"
    dest: "{{ __user_config_file }}"
    validate: "{{ config_item.validate | default(omit) }}"
    mode: "{{ config_item.mode | default('0600') }}"
  when: "'content' in config_item"
