---
- name: file | Generate full path to file
  ansible.builtin.set_fact:
    __user_config_file: "~/{{ config_item.name }}"
- name: file | Create a potential directory
  ansible.builtin.file:
    state: directory
    mode: >-  # add the execution bit
      {{ config_item.mode | default('0700')
      | replace('6', '7') | replace('4', '5') }}
    path: "{{ __user_config_file | dirname }}"
- name: file | Apply the file creation method
  ansible.builtin.include_tasks:
    file: "{{ ('block' in config_item) | ternary('block', 'content') }}.yml"
