---
# defaults file for kickstart_serve

# timeout serving the kickstarts
kickstart_serve_timeout: 3600

# where to find the kickstart file(s)
kickstart_dir: "{{ playbook_dir | dirname }}/ks.myown.d"

# open the listen port (requires root/sudo access)
kickstart_serve_open_port: false

# which port to listen on (default: 8000)
kickstart_serve_listen_port: 8000

# which address to listen on (default: all)
# kickstart_serve_bind_address: 0.0.0.0

# HTTP version to use (default: HTTP/1.0)
# kickstart_serve_http_version: HTTP/1.0
