---
# tasks file for inventory_create
- name: Create inventory directories for the host '{{ inventory_create_hostname }}'
  ansible.builtin.file:
    path: "{{ inventory_create_host_dir }}"
    state: directory
    recurse: true
- name: Gather existing roles
  ansible.builtin.find:
    paths: "{{ playbook_dir | dirname }}/roles"
    depth: 1
    file_type: directory
  register: __inventory_create_roles
- name: Copy each role's defaults/main.yml to the host's vars
  ansible.builtin.copy:
    src: "{{ __inventory_create_role_defs }}"
    dest: "{{ inventory_create_host_dir }}/{{ __inventory_create_role_name }}.yml"
    force: "{{ inventory_create_force }}"
    backup: "{{ inventory_create_backup }}"
    mode: "0640"
  vars:
    __inventory_create_role_defs: "{{ item.path }}/defaults/main.yml"
    __inventory_create_role_name: "{{ item.path | basename }}"
  loop: "{{ __inventory_create_roles.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
- name: Create hosts file
  ansible.builtin.copy:
    # we use multi-line YAML to be sure to have a newline at the end
    content: |
      [{{ inventory_create_default_group }}]
    dest: "{{ inventory_create_base_dir }}/hosts"
    force: false
    backup: "{{ inventory_create_backup }}"
    mode: "0640"
  run_once: true
- name: Add host to hosts file
  ansible.builtin.lineinfile:
    create: true
    # either the variable of the host or the host's inventory name
    line: "{{ hostvars[item]['inventory_create_hostname'] | default(item) }}"
    path: "{{ inventory_create_base_dir }}/hosts"
    insertafter: "^\\[{{ inventory_create_default_group }}\\]$"
    mode: "0640"
  run_once: true
  loop: "{{ ansible_play_hosts }}"
