---
# tasks file for system_software_vscode
# https://computingforgeeks.com/install-visual-studio-code-on-fedora/

- name: make GPG key from Microsoft {{ software_vscode_state }}
  ansible.builtin.rpm_key:
    key: "{{ software_vscode_rpm_key }}"
    state: "{{ software_vscode_state }}"
  become: true

- name: make vscode repository {{ software_vscode_state }}
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: "{{ software_vscode_rpm_repo }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ software_vscode_rpm_key }}"
    state: "{{ software_vscode_state }}"
  become: true

- name: make vscode package {{ software_vscode_state }}
  ansible.builtin.package:
    name: code
    state: "{{ software_vscode_state }}"
  become: true
