---

system_locale_dictionaries_globs:
- /usr/share/myspell/*.aff
- /usr/share/myspell/*.dic
- /usr/share/hyphen/hyph*.dic
- /usr/share/mythes/th*.dat
- /usr/share/mythes/th*.idx

system_locale_dictionaries_globs_tilde:
- /usr/share/myspell/*.aff~
- /usr/share/myspell/*.dic~
- /usr/share/hyphen/hyph*.dic~
- /usr/share/mythes/th*.dat~
- /usr/share/mythes/th*.idx~
