---
# the playbook only creates a kickstart for now but it could do more...
- name: Boot and install the new desktop
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Call kickstart_create role
      ansible.builtin.import_role:
        name: kickstart_create
      tags: kickstart_create
    - name: Call kickstart_serve role
      ansible.builtin.import_role:
        name: kickstart_serve
      tags: kickstart_serve
