---
# a playbook to maintain Fedora up-to-date
# call with `-e fedora_target_release=38` to _upgrade_ to the given version
# else it'll just update the system
- name: Maintain your Fedora system up-to-date
  hosts: all
  gather_facts: true
  become: true

  roles:
    - maintain_uptodate
