---
- name: Call all roles necessary to configure a Fedora system
  hosts: all
  gather_facts: false
  become: true
  pre_tasks:
    - name: Gather existing roles
      ansible.builtin.find:
        paths: "{{ playbook_dir | dirname }}/roles"
        depth: 1
        file_type: directory
        pattern: "system_*"
      register: __system_configure_roles
  tasks:
    - name: Call each system role
      ansible.builtin.include_role:
        name: "{{ __system_configure_role_name }}"
      vars:
        __system_configure_role_name: "{{ role_item.path | basename }}"
      loop: "{{ __system_configure_roles.files }}"
      loop_control:
        label: "{{ role_item.path | basename }}"
        loop_var: role_item
