---
- name: Call all roles necessary to configure the current Fedora user
  hosts: all
  gather_facts: false
  become: false
  pre_tasks:
    - name: Gather existing roles
      ansible.builtin.find:
        paths: "{{ playbook_dir | dirname }}/roles"
        depth: 1
        file_type: directory
        pattern: "user_*"
      register: __user_configure_roles
  tasks:
    - name: Call each user role
      ansible.builtin.include_role:
        name: "{{ __user_configure_role_name }}"
      vars:
        __user_configure_role_name: "{{ role_item.path | basename }}"
      loop: "{{ __user_configure_roles.files }}"
      loop_control:
        label: "{{ role_item.path | basename }}"
        loop_var: role_item
