---
# tasks file for maintain_uptodate
- name: Upgrade all packages from current release
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true
    update_only: true
  become: true
- name: Upgrade Fedora if requested by setting fedora_target_release
  when:
    - fedora_target_release is defined
    - ansible_distribution_major_version is defined
    - (ansible_distribution_major_version | int) < (fedora_target_release | int)
  become: true
  block:  # BLOCK BEGIN
    - name: Install DNF system upgrade plugin package
      ansible.builtin.dnf:
        name: 'dnf-plugin-system-upgrade'
        state: present
    - name: Remove upgrade critical packages if applicable
      ansible.builtin.dnf:
        name: "{{ maintain_uptodate_critical_packages[fedora_target_release | int] }}"
        state: absent
      when: fedora_target_release | int in maintain_uptodate_critical_packages
    - name: Download all necessary for Fedora {{ fedora_target_release }}
      ansible.builtin.command:
        cmd: dnf system-upgrade download --releasever={{ fedora_target_release }} --assumeyes
        warn: false
      changed_when: false  # doesn't really change anything
    - name: Reboot into the upgrade process in fire & forget mode
      ansible.builtin.command:
        cmd: dnf system-upgrade reboot --assumeyes
        warn: false
      async: 60
      poll: 0  # fire & forget mode
      changed_when: true  # always changes something probably
    - name: Wait for the host to shutdown
      ansible.builtin.wait_for:
        host: "{{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}"
        port: "{{ hostvars[inventory_hostname]['ansible_port'] | default(22) }}"
        state: stopped
        timeout: 120
        sleep: 10
      delegate_to: localhost
      become: false
    - name: Wait for host to upgrade and come back
      ansible.builtin.wait_for_connection:
        delay: 600  # more than necessary but gives time for a further reboot in-between
        timeout: 3600  # an upgrade can take up to an hour (?)
        sleep: 60
      become: false
  # BLOCK END
- name: Gather facts to check the (new) current version
  ansible.builtin.setup:
- name: Output the gathered OS version
  ansible.builtin.debug:
    msg: "OS Version is {{ ansible_distribution }} {{ ansible_distribution_version }}"
